### ISSUE TITLE
Auto HUD crash on startup

### ISSUE THREAD

**Issue by BugmanBugman** [Crendgrim/AutoHUD#114]
https://gist.github.com/BugmanBugman/cf4cf8870e7c4c581bbd3b87ca88b114

**Comment by Crendgrim** [comment]
I am unable to replicate this with just AutoHUD installed. What exactly do you mean by "on startup"? The crashlog seems to indicate that a singleplayer world is loaded. Is that correct? What are the exact steps to trigger the crash?

I suspect that this is caused by a mod incompatibility. It would be super helpful if you were able to reduce your installation to a few mods with which it still happens.

**Comment by Crendgrim** [comment]
Try AutoHUD 6.3.5

**Comment by BugmanBugman** [comment]
https://gist.github.com/BugmanBugman/93ba2c4c486e2bf465671c962dda723f
Getting this now when joining a server

**Comment by Crendgrim** [comment]
It's like the mod initialiser is never run, that is very weird
