### ISSUE TITLE
[compatibility] Issue with EMI

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Crendgrim/AutoHUD#28]
Causes some items on EMI to be invisible

**Comment by fzzyhmstrs** [comment]
For reference, this was originally opened and discussed at more length at emilyploszaj/emi/issues/92

**Comment by Crendgrim** [comment]
I have tried to replicate this bug without any success. Are you in fade mode? Does it also happen in move mode?

Your mod list is quite big. A new instance with AutoHUD, EMI, and Sodium works just fine.

**Comment by Aces-and-Jacks** [comment]
Well never mind. Turns out it was Exordium and not autoHUD

**Comment by Aces-and-Jacks** [comment]
So actually it's autoHUD mixed with exordium that causes issues with emi. Not sure if I should reopen or keep closed

**Comment by Aces-and-Jacks** [comment]
https://github.com/tr7zw/Exordium/issues/42

**Comment by Crendgrim** [comment]
Even ignoring this bug, running AutoHUD together with Exordium causes AutoHUD's animations to be super laggy (obviously, due to the lower frame rate). It makes little sense to run a mod to render the GUI at a lower framerate together with a mod that makes the GUI more dynamic. So I will have to close this as a "wontfix" and add Exordium to the list of incompatible mods on the mod page.

**Comment by Aces-and-Jacks** [comment]
Well it's more of just having half the HUD showing (like with health, armor, ect) whether than the animation but I guess if the animation is slow most wouldn't see a point to it

**Comment by Crendgrim** [comment]
I figured out the problem and identified a somewhat hacky fix: never load the special render mixins when not in "fade" mode, as I require a game restart for proper mixin application anyway. I will push that with the next release of AutoHUD.

**Comment by Aces-and-Jacks** [comment]
ok then. Thanks for providing a somewhat compatibility fix
