### ISSUE TITLE
HUD is still rendered although hidden.

### ISSUE THREAD

**Issue by Finsider** [Crendgrim/AutoHUD#97]
This is more of a performance concern from me

When we toggled off 'fade' from autoHUD
The difference in FPS is the same.
![2024-03-13_10 11 57](https://github.com/Crendgrim/AutoHUD/assets/91471471/35fba64e-4bec-4361-bccf-f1ddf9d52432)
![2024-03-13_10 12 07](https://github.com/Crendgrim/AutoHUD/assets/91471471/a77312b4-a667-472c-b836-3f62257b157b)

But when we toggled on 'fade'
![2024-03-13_10 11 48](https://github.com/Crendgrim/AutoHUD/assets/91471471/ac479b95-650b-425e-b410-38cf1374e17c)
![2024-03-13_10 12 20](https://github.com/Crendgrim/AutoHUD/assets/91471471/51d1b85e-d31f-455b-8224-2adfacf6954c)

Expected Behavior: 
Increased FPS while the HUD is hidden (no fade), and 
Not having a performance decrease when HUD is not hidden (yes fade)

If this isn't an issue then I'm sorry regarding these, but this is quite concerning to me

**Comment by Crendgrim** [comment]
For the no fade variant: I did not add a shortcut here to disable rendering because users may configure it to not fully hide. By manually setting how far components move, you could for example set it so the whole HUD moves down so you can just about see your hearts. If I fully skipped rendering, I would need to first do some bounds checking.

As for the fade, I need to render items into a temporary buffer to be able to add transparency. This is mostly necessary because some items like beds still have their own custom renderer rather than using a sprite, and that doesn't play nicely otherwise. I can probably add a shortcut here to skip this step if the current opacity is 100%.

**Comment by Finsider** [comment]
Thing is, I do not have 'move' enabled in the screenshot, I may have misunderstood something but the HUD does get hidden even when both 'move' and 'fade' disabled, without any animation whatsoever, and they're still being rendered (same FPS)

Is it possible to add a shortcut to disable rendering completely when they're hidden completely and not outside of the player' screen, e.g. disable rendering when the opacity are 0%?

**Comment by Crendgrim** [comment]
Ah, right, I never considered that case! Should be trivial to skip rendering if no animation is active.

> Thing is, I do not have 'move' enabled in the screenshot, I may have misunderstood something but the HUD does get hidden even when both 'move' and 'fade' disabled, without any animation whatsoever, and they're still being rendered (same FPS)

Ah, right, I never considered that case! Should be trivial to skip rendering if no animation is active.


> Is it possible to add a shortcut to disable rendering completely when the opacity are 0%? or in this case, when the hud is hidden without having to move outside the screen

Yep, will add that in the next version.

**Comment by Crendgrim** [comment]
While performance would have been on-par with vanilla in the no-animation mode, I have now implemented this in version 6.6. All item rendering is skipped if not necessary (except for the "move but no fade" case, that'll take some more clever logic).

**Comment by Finsider** [comment]
I can't thank you enough for this, I wouldn't expected it to come this early, and yes, the performance did increase when the HUD is hidden now. again, thank you.
